accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('sign-up/', views.user_registration, name = "sign-up"),
    path('sign-in/', views.user_login, name = "sign-in"),
    path('logout/', views.user_logout, name = "logout"),
]

base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('',include('dashboard.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from dashboard import views

app_name = "dashboard"

urlpatterns = [
    path('', views.home, name = "home")
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

    
class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    is_teacher = models.BooleanField(default=False)
    is_student = models.BooleanField(default = False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

class Classroom(models.Model):
    classroom_number = models.CharField(max_length=3, default="1")

    def __str__(self):
        return f'{self.classroom_number}'

class Teacher(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=150, null=True, blank=True)
    school_id = models.CharField(max_length=100, default="0", null=True)
    classrooms  = models.ManyToManyField(Classroom)

    def __str__(self):
        return f'{self.name}'
    
class Student(models.Model):
    user = models.OneToOneField(CustomUser, on_delete= models.CASCADE)
    name = models.CharField(max_length=150, null=True, blank=True)
    roll_number = models.CharField(max_length=4, default = "0")
    classroom = models.ForeignKey(Classroom, on_delete= models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f'{self.name}'

dashboard/models.py
from django.db import models

# Create your models here.

schoolapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from accounts.models import Teacher, Student, Classroom
# Create your models here.



class Assignments(models.Model):
    uploaded_by = models.ForeignKey(Teacher, on_delete=models.SET_NULL, blank=True, null=True)
    upload_to = models.ForeignKey(Classroom, on_delete = models.CASCADE)
    title = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField()
    assignment_field = models.FileField(upload_to="assignments/", null=True, blank=True)
    created_at = models.DateField(auto_now_add=True)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from accounts.models import CustomUser

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(label='username', min_length = 5, max_length=150)
    email = forms.EmailField(label = 'email')
    password1 = forms.CharField(label = "password", widget=forms.PasswordInput)
    password2 = forms.CharField(label = "Confirm password", widget = forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')
    
    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        new = User.objects.filter(username = username)
        if new.count():
            raise ValidationError('User Already Exist')
        return username
    
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        new = User.objects.filter(email = email)
        if new.count():
            raise ValidationError('Email Already Exist')
        return email
    
    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 and password2 and password1!=password2:
            raise ValidationError("Password don't match")
        return password2
    
    def save(self, commit = True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )

        return user

    

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from accounts.forms import CustomUserCreationForm
# Create your views here.
User = get_user_model()

def user_login(request):
    if request.method == "POST":
        email = request.POST.get('email')
        try: 
            account = User.objects.get(email = email)
        except User.DoesNotExist:
            messages.error(request, "Account with this Email doesn't exist")
            return redirect('accounts:sign-in')
        password = request.POST.get('password')
        
        if not account.check_password(password):
            messages.error(request, "Login failed: Password incorrect.")

        user = authenticate(email=email, password = password)
        if user != None:
            login(request, user)
            messages.success(request, "User Logged In.")
            return redirect('dashboard:home')
    return render(request, 'accounts/user-login.html')

def user_registration(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, "User Registered")
            return redirect('accounts:sign-in')
    else:
        form = CustomUserCreationForm()
    
    return render(request, 'accounts/user-register.html', {'form':form})



def user_logout(request):
    logout(request)
    messages.success(request, 'User Logged out!!')
    return redirect('accounts:sign-in')

dashboard/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'dashboard/home.html')

schoolapp/views.py
from django.shortcuts import render

# Create your views here.

accounts/templates/accounts/user-login.html
{% extends 'main.html' %} 

{% block content %}
<div class = "d-flex justify-content-center">
<form method = "POST" >
  {% csrf_token %}
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input
      type="email"
      class="form-control"
      id="exampleInputEmail1"
      aria-describedby="emailHelp"
      name = "email"
    />
    <div id="emailHelp" class="form-text">
      We'll never share your email with anyone else.
    </div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" name = "password" class="form-control" id="exampleInputPassword1" />
  </div>
  <div class="mb-3 form-check">
    <p>Don't have account? <a href = "{% url 'accounts:sign-up' %}">Click here.</a></p>
  </div>
  <button type="submit" class="btn btn-primary">Sign In</button>
</form>
{% endblock content %}

accounts/templates/accounts/user-register.html
{% extends 'main.html' %} 

{% block content %}
<div class = "d-flex justify-content-center">
<form method = "POST" >
  {% csrf_token %}
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input
      type="email"
      class="form-control"
      id="exampleInputEmail1"
      aria-describedby="emailHelp"
      name = "email"
    />
    <div id="emailHelp" class="form-text">
      We'll never share your email with anyone else.
    </div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Username</label>
    <input type="text" name = "username" class="form-control" id="exampleInputPassword1" />
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" name = "password1" class="form-control" id="exampleInputPassword1" />
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Confirm Password</label>
    <input type="password" name = "password2" class="form-control" id="exampleInputPassword1" />
  </div>
  <div class="mb-3 form-check">
    <p>Already have account? <a href = "{% url 'accounts:sign-in' %}">Click here.</a></p>
  </div>
  <button type="submit" class="btn btn-primary">Sign Up</button>
</form>
{% endblock content %}

dashboard/templates/dashboard/home.html
{% extends 'main.html' %}

{% block content %}
{{request.user.email}}
{% endblock content %}

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    {% include 'navbar.html' %}
    <div class = "my-5 mx-5">
        {% block content %}

        {% endblock content%}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
        <ul class="nav-item d-flex">
          <a href = "{% url 'accounts:sign-in'%}" class="btn btn-outline-success">Login</a>
          <a href = "{% url 'accounts:logout'%}" class="btn btn-outline-success">Logout</a>
        </ul>
      </div>
    </div>
  </nav>